<?php
/** @var \App\View\AppView $this */
$this->assign('title', __('Map CSV roles'));
$this->Html->css('workspace', ['block' => true]);
?>
<div class="members upload workspace-page workspace-upload-page">
    <?= $this->element('Members/csv_steps', ['step' => isset($result) ? 4 : 3]) ?>
    <?= $this->element('Workspace/index_header', ['title' => __('Map CSV roles'), 'description' => __('Choose the members to import and map their source roles to existing appointments.'), 'actions' => []]) ?>
    <?php if (isset($result)) : ?>
    <section class="workspace-upload-result" aria-labelledby="import-result-title"><div class="workspace-upload-result-icon" aria-hidden="true">✓</div><div class="workspace-upload-result-content"><p class="workspace-upload-kicker"><?= __('Step 4 of 4 · Import complete') ?></p><h2 id="import-result-title"><?= __('Import summary') ?></h2><div class="workspace-table-panel workspace-import-summary"><div class="table-responsive"><table><thead><tr><th><?= __('Item') ?></th><th><?= __('Result') ?></th></tr></thead><tbody><tr><th scope="row"><?= __('Members') ?></th><td><?= h(__('{0} created', $result['members'])) ?></td></tr><tr><th scope="row"><?= __('Contact methods') ?></th><td><?= h(__('{0} created', $result['contacts'])) ?></td></tr><tr><th scope="row"><?= __('Appointments') ?></th><td><?= h(__('{0} created', $result['appointments'])) ?></td></tr></tbody></table></div></div></div></section>
    <?php if ($result['warnings']) : ?><section class="workspace-upload-panel workspace-import-warnings" aria-labelledby="import-warnings-title"><div class="workspace-panel-intro"><p class="workspace-upload-kicker"><?= __('Import warnings') ?></p><h2 id="import-warnings-title"><?= __('Rows imported with warnings') ?></h2></div><div class="workspace-table-panel workspace-import-summary"><div class="table-responsive"><table><thead><tr><th><?= __('Warning') ?></th></tr></thead><tbody><?php foreach ($result['warnings'] as $warning) : ?><tr class="workspace-import-warning"><td><?= h($warning) ?></td></tr><?php endforeach; ?></tbody></table></div></div></section><?php endif; ?>
    <section class="workspace-upload-panel workspace-role-results" aria-labelledby="role-results-title"><div class="workspace-panel-intro"><p class="workspace-upload-kicker"><?= __('Role import results') ?></p><h2 id="role-results-title"><?= __('Role import outcomes') ?></h2><p><?= __('Each source role row attempted in this import is shown below.') ?></p></div><div class="workspace-table-panel workspace-mapping-table"><div class="table-responsive"><table><thead><tr><th><?= __('CSV unit / parent team') ?></th><th><?= __('CSV team') ?></th><th><?= __('CSV role / role type') ?></th><th><?= __('Rows') ?></th><th><?= __('Result') ?></th></tr></thead><tbody><?php foreach ($roleResults as $roleResult) : ?><tr><td><?= h(implode(' / ', array_filter([$roleResult['unit'], $roleResult['parent']]))) ?></td><td><?= h($roleResult['team']) ?></td><td><?= h(($roleResult['role'] ?: __('blank')) . ' / ' . ($roleResult['type'] ?: __('blank'))) ?></td><td><span class="workspace-row-count"><?= h($roleResult['count']) ?></span></td><td><span class="workspace-role-result workspace-role-result-<?= h($roleResult['status']) ?>"><?= match ($roleResult['status']) { 'successful' => __('Successful'), 'unmapped' => __('Members and contacts only'), 'skipped' => __('Skipped'), default => __('Failed'), } ?></span><span class="workspace-role-result-detail"><?= h(__($roleResult['detail'])) ?></span></td></tr><?php endforeach; ?></tbody></table></div></div><div class="workspace-form-footer workspace-import-footer"><?= $this->Html->link(__('Back to members'), ['action' => 'index'], ['class' => 'button']) ?><?= $this->Html->link(__('Upload another CSV'), ['action' => 'upload'], ['class' => 'button button-outline']) ?></div></section>
    <?php else : ?>
    <section class="workspace-upload-panel workspace-mapping-panel" aria-labelledby="role-mapping-title">
        <div class="workspace-panel-intro"><p class="workspace-upload-kicker"><?= __('Step 3 of 4') ?></p><h2 id="role-mapping-title"><?= __('Map CSV roles') ?></h2><p><?= __('Unit mappings are already saved. Review role mappings before importing members.') ?></p></div>
        <?php if (!array_filter($roleOptions)) :
            ?><p class="workspace-upload-notice"><?= __('Create teams and roles in the app before mapping appointments.') ?></p><?php
        endif; ?>
        <?= $this->Form->create(null, ['id' => 'role-mapping-form']) ?><?= $this->Form->hidden('token', ['value' => $token]) ?>
        <?php $renderUnitOptions = function (array $units, string $category): void { foreach ($units as $value => $unit) : ?>
            <label><input type="checkbox" name="units[]" value="<?= h($value) ?>" checked data-unit-category="<?= $category ?>"><span><?= h($unit) ?></span></label><?php
        endforeach; }; ?>
        <fieldset id="mapping-unit-filter-controls" class="workspace-unit-filter"><legend><?= __('Units to import') ?></legend><p><?= __('All members and contacts in selected units will be imported. Unmapped roles do not create appointments.') ?></p><?= $this->Form->hidden('units', ['value' => '']) ?>
            <section class="workspace-unit-filter-area"><div class="workspace-unit-filter-heading"><h3><?= __('District') ?></h3><div class="workspace-unit-actions"><button type="button" class="button button-outline" data-unit-selection="all" data-unit-category="district"><?= __('Select district') ?></button><button type="button" class="button button-clear" data-unit-selection="none" data-unit-category="district"><?= __('Deselect district') ?></button></div></div><div class="workspace-unit-options"><?php $renderUnitOptions($unitFilters['district'], 'district') ?></div></section>
            <section class="workspace-unit-filter-area"><div class="workspace-unit-filter-heading"><h3><?= __('District sections') ?></h3><div class="workspace-unit-actions"><button type="button" class="button button-outline" data-unit-selection="all" data-unit-category="sections"><?= __('Select all sections') ?></button><button type="button" class="button button-clear" data-unit-selection="none" data-unit-category="sections"><?= __('Unselect all sections') ?></button></div></div><?php foreach ($unitFilters['district_sections'] as $section) : ?><div class="workspace-unit-filter-branch"><h4><?= h($section['label']) ?></h4><div class="workspace-unit-options"><?php $renderUnitOptions($section['units'], 'sections') ?></div></div><?php endforeach; ?></section>
            <section class="workspace-unit-filter-area"><div class="workspace-unit-filter-heading"><h3><?= __('Groups') ?></h3><div class="workspace-unit-actions"><button type="button" class="button button-outline" data-unit-selection="all" data-unit-category="groups"><?= __('Select all groups') ?></button><button type="button" class="button button-clear" data-unit-selection="none" data-unit-category="groups"><?= __('Unselect all groups') ?></button></div></div><?php foreach ($unitFilters['groups'] as $group) : ?><section class="workspace-unit-filter-branch"><h4><?= h($group['label']) ?></h4><div class="workspace-unit-options"><?php $renderUnitOptions($group['units'], 'groups') ?></div><?php if ($group['sections']) : ?><div class="workspace-unit-filter-children"><h5><?= __('Sections') ?></h5><?php foreach ($group['sections'] as $section) : ?><div class="workspace-unit-filter-branch"><h6><?= h($section['label']) ?></h6><div class="workspace-unit-options"><?php $renderUnitOptions($section['units'], 'sections') ?></div></div><?php endforeach; ?></div><?php endif; ?></section><?php endforeach; ?></section>
            <p id="mapping-unit-summary" class="workspace-unit-summary" role="status" aria-live="polite"></p></fieldset>
        <div class="workspace-mapping-heading workspace-role-heading"><div><p class="workspace-upload-kicker"><?= __('Role mapping') ?></p><h3><?= __('Map CSV roles') ?></h3></div><p><?= __('Connect source roles to existing team and role combinations.') ?></p></div>
        <?php $renderRoleRow = function (string $key, array $source) use ($savedMappings, $roleOptions): void { $mapping = $savedMappings[$key] ?? ''; $state = $mapping === 'skip' ? 'skipped' : ($mapping === '' ? 'unmapped' : 'mapped'); ?><tr data-unit="<?= h('unit:' . $source['unit']) ?>" data-mapping-state="<?= $state ?>" class="<?= $state === 'unmapped' ? 'workspace-unmapped-row' : ($state === 'skipped' ? 'workspace-skipped-row' : '') ?>"><td><?= h(implode(' / ', array_filter([$source['unit'], $source['parent']]))) ?></td><td><?= h($source['team']) ?></td><td><?= h(($source['role'] ?: __('blank')) . ' / ' . ($source['type'] ?: __('blank'))) ?></td><td><span class="workspace-row-count"><?= h($source['count']) ?></span></td><td><?= $this->Form->control('mapping.' . $key, ['type' => 'select', 'label' => false, 'aria-label' => __('Destination for {0} / {1}', $source['team'], $source['role']), 'options' => ['skip' => __('Skip appointment')] + ($roleOptions[$key] ?? []), 'empty' => __('Members and contacts only (unmapped)'), 'default' => $mapping]) ?><span class="workspace-mapping-status workspace-skipped-status"<?= $mapping === 'skip' ? '' : ' hidden' ?>><?= __('Skipped — no appointment') ?></span></td></tr><?php }; ?>
        <div class="workspace-mapping-grids">
            <section class="workspace-mapping-grid"><h3><?= __('Unmapped roles') ?></h3><div class="workspace-table-panel workspace-mapping-table"><div class="table-responsive"><table><thead><tr><th><?= __('CSV unit / parent team') ?></th><th><?= __('CSV team') ?></th><th><?= __('CSV role / role type') ?></th><th><?= __('Rows') ?></th><th><?= __('Existing team / role') ?></th></tr></thead><tbody id="unmapped-mapping-rows"><?php foreach ($sources as $key => $source) : ?><?php if (($savedMappings[$key] ?? '') === '') : ?><?php $renderRoleRow($key, $source) ?><?php endif; ?><?php endforeach; ?></tbody></table></div></div></section>
            <details class="workspace-mapping-grid workspace-mapped-grid"><summary><?= __('Mapped roles') ?> <span id="mapped-count"><?= count(array_filter($savedMappings)) ?></span></summary><div class="workspace-table-panel workspace-mapping-table"><div class="table-responsive"><table><thead><tr><th><?= __('CSV unit / parent team') ?></th><th><?= __('CSV team') ?></th><th><?= __('CSV role / role type') ?></th><th><?= __('Rows') ?></th><th><?= __('Existing team / role') ?></th></tr></thead><tbody id="mapped-mapping-rows"><?php foreach ($sources as $key => $source) : ?><?php if (($savedMappings[$key] ?? '') !== '') : ?><?php $renderRoleRow($key, $source) ?><?php endif; ?><?php endforeach; ?></tbody></table></div></div></details>
        </div>
        <div class="workspace-form-footer workspace-import-footer"><?= $this->Form->button(__('Import selected units')) ?><?= $this->Html->link(__('Start again with another CSV'), ['action' => 'upload'], ['class' => 'button button-outline']) ?></div>
        <?= $this->Form->end() ?><?= $this->Html->script('member-csv-mapping', ['defer' => true]) ?>
    </section>
    <?php endif; ?>
</div>
