apiVersion: v1
kind: ConfigMap
metadata:
  name: district-team-config
  namespace: district-team
data:
  APP_NAME: district-team
  APP_ENCODING: UTF-8
  APP_DEFAULT_LOCALE: en_GB
  APP_DEFAULT_TIMEZONE: Europe/London
  APP_FULL_BASE_URL: https://district-team.example.com
  DEBUG: "false"
  TRUSTEE_BOARD_TARGET_APPOINTMENTS: "8"
  DATABASE_HOST: district-team-postgres
  DATABASE_PORT: "5432"
