apiVersion: batch/v1
kind: Job
metadata:
  name: district-team-migrate
  namespace: district-team
spec:
  template:
    spec:
      serviceAccountName: prod-district-team-runtime
      containers:
        - name: migrate
          envFrom:
            - configMapRef:
                name: prod-district-team-config
            - secretRef:
                name: prod-district-team-secrets
