apiVersion: v1
kind: Service
metadata:
  name: district-team-postgres
  namespace: district-team
spec:
  type: ClusterIP
  selector:
    app: district-team-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
