apiVersion: onepassword.com/v1
kind: OnePasswordItem
type: kubernetes.io/dockerconfigjson
metadata:
  name: ghcr-pull-secret
  namespace: district-team
spec:
  itemPath: vaults/Infrastructure/items/ArgoCD - LBD Repo Creds
