apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: district-team-secrets
  namespace: district-team
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/Infrastructure/items/DistrictTeam
